version: '3.1'
services: 
  mongo:
    image: mongo:4-bionic
    ports:
      - "27117:27017"
    volumes:
      - "mongoconfig:/data/configdb" 
      - "mongodb:/data/db"

volumes:
  mongoconfig:
  mongodb:
